### ISSUE TITLE
Loads of compile errors

### ISSUE THREAD

**Issue by kkjamie** [NFMynster/ArenaGame#6]
I cloned master, opened it in unity 2018.1.3f1. It has 39 compile errors all referencing missing TextMeshPro stuff. I deleted text mesh pro and got it from the package manager instead. That fixed them but of course the scenes are all broken now, all the old TextMesh components are now missing references.

![image](https://user-images.githubusercontent.com/5612566/42620207-3c49312c-85b2-11e8-816b-d90ea0a20b5e.png)

Also the compiled windows build doesn't work. "Failed to Load mono"

So have I done something really stupidly obvious or is the project just currently in this state.

**Comment by NFMynster** [comment]
Did you fix it?
