### ISSUE TITLE
MinAttribute ambiguous errors

### ISSUE THREAD

**Issue by Youdaman** [NFMynster/ArenaGame#7]
In 2018.3.1f1 the following file throws 3 errors about `MinAttribute` being ambiguous: ArenaGame\Assets\PostProcessing\Editor\PropertyDrawers\MinDrawer.cs

The "fix" is to change the 3 occurances of `MinAttribute` to either `UnityEngine.MinAttribute` or `UnityEngine.PostProcessing.MinAttribute` to remove the ambiguity. Not sure which is correct, either seems to get rid of the errors.

Guessing it's to do with the version of Post Processing included.

**Comment by NFMynster** [comment]
Indeed so, this project is using the old v1 post processing.
